name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     compiler: [gcc, clang]
    #     os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - name: install-boost
      run: |
        sudo apt-get update
        sudo apt-get install libboost-all-dev
    - name: make
      run: make
    - name: buechi01
      run: ./driver examples/buechi01.aut --verbose=3
    - name: test
      run: VERBOSE=3 ./test
